name: clima
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  http: ^1.1.0
  intl: ^0.17.0
  sleek_circular_slider: ^2.0.1
  google_maps_flutter: ^2.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation/.
    - assets/images/.
